[pytest]
DJANGO_SETTINGS_MODULE = yanews.settings

addopts = -s -v

filterwarnings =
    ignore:ast\.(Str|NameConstant|Num) is deprecated and will be removed in Python 3\.14; use ast\.Constant instead:DeprecationWarning
    ignore:Attribute s is deprecated and will be removed in Python 3\.14; use value instead:DeprecationWarning

testpaths = news/pytest_tests/